openapi: 3.0.3
info:
  title: Java女子部ハンズオン メモAPI
  description: |-
    Java女子部のSpring Bootハンズオンで作成するメモAPIの仕様書です
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /memos:
    get:
      summary: メモの一覧を取得
      operationId: getMemos
      tags:
        - Memo
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memo'
        '400':
          description: Bad request
    post:
      summary: 新しいメモを作成
      operationId: createMemo
      tags:
        - Memo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: 本文
                userId:
                  type: integer
                  format: int64
                  description: メモを作成するユーザーID
              required:
                - body
                - userId
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
        '400':
          description: Bad request
  /memos/{memo_id}:
    get:
      summary: 特定のメモの詳細を取得
      operationId: getMemoById
      tags:
        - Memo
      parameters:
        - in: path
          name: memo_id
          required: true
          schema:
            type: integer
            format: int64
          description: 取得したいメモのID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
        '404':
          description: Not found
    delete:
      summary: 特定のメモを削除
      operationId: deleteMemoById
      tags:
        - Memo
      parameters:
        - in: path
          name: memo_id
          required: true
          schema:
            type: integer
            format: int64
          description: 削除したいメモのID
      responses:
        '204':
          description: Success
        '404':
          description: Not found
    patch:
      summary: 特定のメモの内容を更新
      operationId: updateMemoById
      tags:
        - Memo
      parameters:
        - in: path
          name: memo_id
          required: true
          schema:
            type: integer
            format: int64
          description: 更新したいメモのID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: 更新後の本文
              required:
                - body
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memo'
        '400':
          description: Bad request
        '404':
          description: Not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ユーザーID
        emailAddress:
          type: string
          format: email
          description: ユーザーのメールアドレス
        userName:
          type: string
          description: ユーザー名
      required:
        - emailAddress
        - userName
    Memo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: メモID
        createdAt:
          type: string
          format: date-time
          description: 作成日時
        body:
          type: string
          description: 本文
        user:
          $ref: '#/components/schemas/User'
      required:
        - createdAt
        - body
        - user
